services:
  - type: web
    name: raganork-md
    env: node
    branch: main
    repo: https://github.com/souravkl11/raganork-md
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION
        sync: false
      - key: MODE
        value: false
      - key: PORT
        value: 3000
      - key: SUDO
        value: false
      - key: ALIVE
        value: false
      - key: CHATBOT
        value: false
      - key: BOT_INFO
        value: false
      - key: HANDLERS
        value: .
      - key: STICKER_DATA
        value: false
